2018-09-26 17:13:14,522 ERROR 40003 [-/127.0.0.1/-/188ms POST /users/] nodejs.SequelizeDatabaseError: Table 'tracker.users' doesn't exist
    at Query.formatError (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:513:28)
    at PacketParser.onPacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/packet_parser.js:76:14)
    at Socket.<anonymous> (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/debuggability.js:411:19)
    at Promise._then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:232:17)
    at Promise.then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:125:17)
    at model.save (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:3670:8)
    at Function.create (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:2033:8)
    at User.create (/work/test/egg-example/app/service/user.js:23:32)
    at UserController.create (/work/test/egg-example/app/controller/user.js:22:41)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:13:14','2018-09-26 09:13:14');"}
original: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:13:14','2018-09-26 09:13:14');"}
sql: "INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:13:14','2018-09-26 09:13:14');"
pid: 40003
hostname: ksdeMacBook-Pro-2.local

2018-09-26 17:15:04,911 ERROR 40031 [-/127.0.0.1/-/183ms POST /users/] nodejs.SequelizeDatabaseError: Table 'tracker_development.users' doesn't exist
    at Query.formatError (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:513:28)
    at PacketParser.onPacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/packet_parser.js:76:14)
    at Socket.<anonymous> (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/debuggability.js:411:19)
    at Promise._then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:232:17)
    at Promise.then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:125:17)
    at model.save (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:3670:8)
    at Function.create (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:2033:8)
    at User.create (/work/test/egg-example/app/service/user.js:23:32)
    at UserController.create (/work/test/egg-example/app/controller/user.js:22:41)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker_development.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:15:04','2018-09-26 09:15:04');"}
original: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker_development.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:15:04','2018-09-26 09:15:04');"}
sql: "INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:15:04','2018-09-26 09:15:04');"
pid: 40031
hostname: ksdeMacBook-Pro-2.local

2018-09-26 17:35:06,128 ERROR 40274 [-/127.0.0.1/-/219ms POST /users/] nodejs.SequelizeDatabaseError: Table 'tracker_development.users' doesn't exist
    at Query.formatError (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:513:28)
    at PacketParser.onPacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/packet_parser.js:76:14)
    at Socket.<anonymous> (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/debuggability.js:411:19)
    at Promise._then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:232:17)
    at Promise.then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:125:17)
    at model.save (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:3670:8)
    at Function.create (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:2033:8)
    at User.create (/work/test/egg-example/app/service/user.js:23:32)
    at UserController.create (/work/test/egg-example/app/controller/user.js:22:41)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker_development.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (DEFAULT,'aaa',11,'2018-09-26 09:35:05','2018-09-26 09:35:05');"}
original: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker_development.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (DEFAULT,'aaa',11,'2018-09-26 09:35:05','2018-09-26 09:35:05');"}
sql: "INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (DEFAULT,'aaa',11,'2018-09-26 09:35:05','2018-09-26 09:35:05');"
pid: 40274
hostname: ksdeMacBook-Pro-2.local

2018-09-26 17:35:22,211 ERROR 40274 [-/127.0.0.1/-/778ms POST /users/] nodejs.SequelizeDatabaseError: Table 'tracker_development.users' doesn't exist
    at Query.formatError (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:513:28)
    at PacketParser.onPacket (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/packet_parser.js:76:14)
    at Socket.<anonymous> (/work/test/egg-example/node_modules/.1.6.1@mysql2/lib/connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/debuggability.js:411:19)
    at Promise._then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:232:17)
    at Promise.then (/work/test/egg-example/node_modules/.3.5.2@bluebird/js/release/promise.js:125:17)
    at model.save (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:3670:8)
    at Function.create (/work/test/egg-example/node_modules/.4.39.0@sequelize/lib/model.js:2033:8)
    at User.create (/work/test/egg-example/app/service/user.js:23:32)
    at UserController.create (/work/test/egg-example/app/controller/user.js:22:41)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker_development.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:35:21','2018-09-26 09:35:21');"}
original: {"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","sqlMessage":"Table 'tracker_development.users' doesn't exist","sql":"INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:35:21','2018-09-26 09:35:21');"}
sql: "INSERT INTO `users` (`id`,`name`,`age`,`created_at`,`updated_at`) VALUES (1,'aaa',11,'2018-09-26 09:35:21','2018-09-26 09:35:21');"
pid: 40274
hostname: ksdeMacBook-Pro-2.local

2018-09-26 19:39:17,007 ERROR 40472 nodejs.ClusterClientNoResponseError: client no response in 4385385ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 40472
hostname: ksdeMacBook-Pro-2.local

2018-09-27 06:27:47,856 ERROR 40472 nodejs.ClusterClientNoResponseError: client no response in 38910818ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 40472
hostname: ksdeMacBook-Pro-2.local

2018-09-27 09:24:10,199 ERROR 40472 nodejs.ClusterClientNoResponseError: client no response in 10581743ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 40472
hostname: ksdeMacBook-Pro-2.local

2018-09-27 09:37:44,460 ERROR 40472 nodejs.ClusterClientNoResponseError: client no response in 813963ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 40472
hostname: ksdeMacBook-Pro-2.local

2018-09-27 13:40:18,118 ERROR 40472 nodejs.ClusterClientNoResponseError: client no response in 1937390ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 40472
hostname: ksdeMacBook-Pro-2.local

2018-09-27 16:28:07,238 ERROR 45540 [-/127.0.0.1/-/22ms POST /accounts/] nodejs.ReferenceError: msg is not defined
    at Function.error (/work/test/egg-example/app/util/serverResponse.js:14:40)
    at checkLogin (/work/test/egg-example/app/middleware/checkLogin.js:5:62)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at nosniff (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/nosniff.js:8:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at noopen (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/noopen.js:8:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at notAllow (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/methodnoallow.js:21:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:34:12
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45540
hostname: ksdeMacBook-Pro-2.local

2018-09-27 16:33:07,392 ERROR 45590 [-/127.0.0.1/-/22ms POST /accounts/register] nodejs.TypeError: Cannot read property 'register' of undefined
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)

pid: 45590
hostname: ksdeMacBook-Pro-2.local

2018-09-27 16:55:12,992 ERROR 45788 [-/127.0.0.1/-/22ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:9:39)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:19:27)
    at Account.register (/work/test/egg-example/app/service/account.js:50:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45788
hostname: ksdeMacBook-Pro-2.local

2018-09-27 16:58:10,109 ERROR 45829 [-/127.0.0.1/-/19ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:9:39)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:19:27)
    at Account.register (/work/test/egg-example/app/service/account.js:50:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45829
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:01:40,937 ERROR 45862 [-/127.0.0.1/-/23ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:16:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:26:27)
    at Account.register (/work/test/egg-example/app/service/account.js:57:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45862
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:02:02,411 ERROR 45862 [-/127.0.0.1/-/1ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:16:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:26:27)
    at Account.register (/work/test/egg-example/app/service/account.js:57:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45862
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:02:55,272 ERROR 45872 [-/127.0.0.1/-/26ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:17:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:27:27)
    at Account.register (/work/test/egg-example/app/service/account.js:58:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45872
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:03:31,505 ERROR 45878 [-/127.0.0.1/-/23ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:17:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:27:27)
    at Account.register (/work/test/egg-example/app/service/account.js:58:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45878
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:05:14,500 ERROR 45892 [-/127.0.0.1/-/25ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:17:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:27:27)
    at Account.register (/work/test/egg-example/app/service/account.js:58:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45892
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:06:05,490 ERROR 45898 [-/127.0.0.1/-/27ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:18:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:28:27)
    at Account.register (/work/test/egg-example/app/service/account.js:59:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45898
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:07:24,178 ERROR 45932 [-/127.0.0.1/-/21ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:17:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:27:27)
    at Account.register (/work/test/egg-example/app/service/account.js:58:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45932
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:08:04,518 ERROR 45940 [-/127.0.0.1/-/19ms POST /accounts/register] nodejs.TypeError: Cannot read property 'findOne' of undefined
    at Account._checkExistByField (/work/test/egg-example/app/service/account.js:17:42)
    at Account.checkValid (/work/test/egg-example/app/service/account.js:27:27)
    at Account.register (/work/test/egg-example/app/service/account.js:58:40)
    at AccountController.register (/work/test/egg-example/app/controller/account.js:30:47)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)

pid: 45940
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:11:43,081 ERROR 45975 [-/127.0.0.1/-/199ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 45975
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:12:17,299 ERROR 45980 [-/127.0.0.1/-/187ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 45980
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:12:57,248 ERROR 45980 [-/127.0.0.1/-/3417ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 45980
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:13:16,790 ERROR 45991 [-/127.0.0.1/-/177ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:60:34)
    at <anonymous>

pid: 45991
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:15:38,030 ERROR 46004 [-/127.0.0.1/-/2435ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:60:34)
    at <anonymous>

pid: 46004
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:17:57,987 ERROR 46029 [-/127.0.0.1/-/280ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 46029
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:18:16,870 ERROR 46032 [-/127.0.0.1/-/182ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 46032
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:18:29,956 ERROR 46035 [-/127.0.0.1/-/207ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 46035
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:19:09,842 ERROR 46040 [-/127.0.0.1/-/639ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:61:34)
    at <anonymous>

pid: 46040
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:19:59,602 ERROR 46048 [-/127.0.0.1/-/400ms POST /accounts/register] nodejs.TypeError: Cannot read property 'error' of undefined
    at Account.register (/work/test/egg-example/app/service/account.js:62:34)
    at <anonymous>

pid: 46048
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:48:49,869 ERROR 46351 [-/127.0.0.1/-/25ms POST /accounts/login] nodejs.SyntaxError: Identifier 'account' has already been declared
    at AccountController.login (/work/test/egg-example/app/controller/account.js:37:49)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/index.js:36:21)
    at wrappedController (/work/test/egg-example/node_modules/.4.10.2@egg-core/lib/utils/router.js:322:18)
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at next (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:45:18)
    at /work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:346:16
    at dispatch (/work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:44:32)
    at /work/test/egg-example/node_modules/.3.2.1@koa-compose/index.js:36:12
    at dispatch (/work/test/egg-example/node_modules/.7.4.0@koa-router/lib/router.js:351:31)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at /work/test/egg-example/node_modules/.2.4.1@egg-development/app/middleware/egg_loader_trace.js:9:56
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at i18n (/work/test/egg-example/node_modules/.2.0.0@egg-i18n/app/middleware/i18n.js:13:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at dta (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/dta.js:12:12)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xframe (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xframe.js:7:11)
    at dispatch (/work/test/egg-example/node_modules/.4.1.0@koa-compose/index.js:42:32)
    at xssProtection (/work/test/egg-example/node_modules/.2.4.0@egg-security/lib/middlewares/xssProtection.js:7:11)

pid: 46351
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:49:29,921 ERROR 46359 [-/127.0.0.1/-/175ms POST /accounts/login] nodejs.Error: Illegal argument undefined
    at module.exports (/work/test/egg-example/node_modules/.2.2.1@md5/md5.js:152:13)
    at Account.login (/work/test/egg-example/app/service/account.js:115:21)
    at <anonymous>

pid: 46359
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:50:14,989 ERROR 46364 [-/127.0.0.1/-/178ms POST /accounts/login] nodejs.Error: Illegal argument undefined
    at module.exports (/work/test/egg-example/node_modules/.2.2.1@md5/md5.js:152:13)
    at Account.login (/work/test/egg-example/app/service/account.js:116:21)
    at <anonymous>

pid: 46364
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:52:49,428 ERROR 46387 [-/127.0.0.1/-/357ms POST /accounts/login] nodejs.TypeError: Assignment to constant variable.
    at Account.login (/work/test/egg-example/app/service/account.js:121:15)
    at <anonymous>

pid: 46387
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:52:52,863 ERROR 46387 [-/127.0.0.1/-/331ms POST /accounts/login] nodejs.TypeError: Assignment to constant variable.
    at Account.login (/work/test/egg-example/app/service/account.js:121:15)
    at <anonymous>

pid: 46387
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:53:20,820 ERROR 46393 [-/127.0.0.1/-/330ms POST /accounts/login] nodejs.TypeError: Cannot set property 'currentUser' of undefined
    at AccountController.login (/work/test/egg-example/app/controller/account.js:40:32)
    at <anonymous>

pid: 46393
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:53:47,829 ERROR 46397 [-/127.0.0.1/-/340ms POST /accounts/login] nodejs.TypeError: Assignment to constant variable.
    at Account.login (/work/test/egg-example/app/service/account.js:122:15)
    at <anonymous>

pid: 46397
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:54:17,584 ERROR 46401 [-/127.0.0.1/-/369ms POST /accounts/login] nodejs.TypeError: Assignment to constant variable.
    at Account.login (/work/test/egg-example/app/service/account.js:122:15)
    at <anonymous>

pid: 46401
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:54:58,611 ERROR 46406 [-/127.0.0.1/-/905ms POST /accounts/login] nodejs.TypeError: account.dataValues.toJSON is not a function
    at Account.login (/work/test/egg-example/app/service/account.js:121:36)
    at <anonymous>

pid: 46406
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:55:14,829 ERROR 46410 [-/127.0.0.1/-/360ms POST /accounts/login] nodejs.TypeError: Cannot set property 'currentUser' of undefined
    at AccountController.login (/work/test/egg-example/app/controller/account.js:40:32)
    at <anonymous>

pid: 46410
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:55:46,525 ERROR 46415 [-/127.0.0.1/-/345ms POST /accounts/login] nodejs.TypeError: Assignment to constant variable.
    at Account.login (/work/test/egg-example/app/service/account.js:122:15)
    at <anonymous>

pid: 46415
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:56:06,954 ERROR 46419 [-/127.0.0.1/-/346ms POST /accounts/login] nodejs.TypeError: Assignment to constant variable.
    at Account.login (/work/test/egg-example/app/service/account.js:122:15)
    at <anonymous>

pid: 46419
hostname: ksdeMacBook-Pro-2.local

2018-09-27 17:56:59,060 ERROR 46427 [-/127.0.0.1/-/357ms POST /accounts/login] nodejs.TypeError: Cannot set property 'currentUser' of undefined
    at AccountController.login (/work/test/egg-example/app/controller/account.js:40:32)
    at <anonymous>

pid: 46427
hostname: ksdeMacBook-Pro-2.local

2018-09-27 19:46:24,769 ERROR 45930 nodejs.ClusterClientNoResponseError: client no response in 3947784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 45930
hostname: ksdeMacBook-Pro-2.local

2018-09-28 09:24:43,060 ERROR 47175 nodejs.ClusterClientNoResponseError: client no response in 40268489ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 47175
hostname: ksdeMacBook-Pro-2.local

2018-09-28 09:41:01,715 ERROR 47175 nodejs.ClusterClientNoResponseError: client no response in 978044ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 47175
hostname: ksdeMacBook-Pro-2.local

2018-09-28 19:15:23,778 ERROR 75484 nodejs.ClusterClientNoResponseError: client no response in 238933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 75484
hostname: ksdeMacBook-Pro-2.local

2018-09-28 19:29:40,051 ERROR 75484 nodejs.ClusterClientNoResponseError: client no response in 376159ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 75484
hostname: ksdeMacBook-Pro-2.local

2018-09-28 19:51:45,779 ERROR 75484 nodejs.ClusterClientNoResponseError: client no response in 1305718ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 75484
hostname: ksdeMacBook-Pro-2.local

2018-09-28 20:11:46,179 ERROR 75484 nodejs.ClusterClientNoResponseError: client no response in 1180389ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 75484
hostname: ksdeMacBook-Pro-2.local

2018-09-28 21:10:17,018 ERROR 80794 nodejs.ClusterClientNoResponseError: client no response in 299402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 80794
hostname: ksdeMacBook-Pro-2.local

2018-09-28 22:16:32,009 ERROR 80794 nodejs.ClusterClientNoResponseError: client no response in 260312ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 80794
hostname: ksdeMacBook-Pro-2.local

2018-09-28 22:23:23,849 ERROR 80794 nodejs.ClusterClientNoResponseError: client no response in 111760ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 80794
hostname: ksdeMacBook-Pro-2.local

2018-09-29 09:22:13,945 ERROR 80794 nodejs.ClusterClientNoResponseError: client no response in 37609666ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/work/test/egg-example/node_modules/.2.1.1@cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: "ClusterClientNoResponseError"
pid: 80794
hostname: ksdeMacBook-Pro-2.local

